### Регистрация нового пользователя
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "salimla",
  "password": "12345678",
  "email": "john.doe@example.com",
  "firstName": "Роман",
  "lastName": "Салимов",
  "phoneNumber": "+1234567890"
}

###Вхож
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "salimla",
  "password": "12345678"
}

### Создание аккаунта для текущего пользователя
POST http://localhost:8080/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYWxpbWxhIiwiaWF0IjoxNzUzMzExOTMzLCJleHAiOjE3NTMzMTU1MzN9.W5PCxmUqI6ai8mbe4PIETSHUIRvISHGjPd5uEAfw_EA
Content-Type: application/json

{
  "balance": 0,
  "blocked": false
}

### Создание аккаунта для текущего пользователя
POST http://localhost:8080/api/account/transferByAccountId
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYWxpbWxhIiwiaWF0IjoxNzUzMjIxNjA2LCJleHAiOjE3NTMyMjUyMDZ9.jQgn3ZjIhFIOB_6y0Hz9O3yQs99ToAE1QpJWzW9tTn4
Content-Type: application/json

{
  "fromAccId": 31581439,
  "toAccId": 1234567,
  "amount": 300,
  "comment": "string"
}
