### Создать кредитный счёт (только ADMIN)
POST http://localhost:8080/api/credit-accounts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NzUxNzg4MSwiZXhwIjoxNzU3NTIxNDgxfQ.16ExNTgPh9XcoO6J6vzKyW0yb30j3Nt1WR1A0kKSMkQ
Content-Type: application/json

{
  "userID": 1,
  "creditLimit": 5000,
  "interestRate": 15.5,
  "gracePeriod": 30
}

### Пополнить кредитный счёт
POST http://localhost:8080/api/credit-accounts/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyIiwiaWF0IjoxNzU3NTIzMDIyLCJleHAiOjE3NTc1MjY2MjJ9.twJccO_2gaEyLW8wxW-koXD5y9diQct8vGkMTTtC2KE
Content-Type: application/json

{
  "accountNumber": "4674462529",
  "amount": 1000
}

### Снять с кредитного счёта
POST http://localhost:8080/api/credit-accounts/withdraw
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyIiwiaWF0IjoxNzU3NTIzMDIyLCJleHAiOjE3NTc1MjY2MjJ9.twJccO_2gaEyLW8wxW-koXD5y9diQct8vGkMTTtC2KE
Content-Type: application/json

{
  "accountNumber": "4674462529",
  "amount": 500
}

### Перевести с кредитного счёта
POST http://localhost:8080/api/credit-accounts/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXd1c2VyIiwiaWF0IjoxNzU3NTIzMDIyLCJleHAiOjE3NTc1MjY2MjJ9.twJccO_2gaEyLW8wxW-koXD5y9diQct8vGkMTTtC2KE
Content-Type: application/json

{
  "fromAccount": "4674462529",
  "toAccount": "7812293466",
  "amount": 4000,
  "comment": "Погашение долга"
}

### Удалить кредитный счёт (только ADMIN)
DELETE http://localhost:8080/api/credit-accounts/2483866427
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NzUxNTkxOCwiZXhwIjoxNzU3NTE5NTE4fQ.CqSAfBzH16CfPFB4KcGzZ64CZRHdhX5B7d1KHBpcSZ8

### Увеличить лимит (только ADMIN)
PUT http://localhost:8080/api/credit-accounts/4674462529/increase-limit?newLimit=7000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1NzUxNzg4MSwiZXhwIjoxNzU3NTIxNDgxfQ.16ExNTgPh9XcoO6J6vzKyW0yb30j3Nt1WR1A0kKSMkQ

### Уменьшить лимит (только ADMIN)
PUT http://localhost:8080/api/credit-accounts/1/decrease-limit?newLimit=3000
Authorization: Bearer <ADMIN_JWT>

### Изменить процентную ставку (только ADMIN)
PUT http://localhost:8080/api/credit-accounts/1/set-interest?newRate=19.9
Authorization: Bearer <ADMIN_JWT>
