### Регистрация пользователя
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123",
  "email": "test@example.com",
  "firstName": "Test",
  "lastName": "User",
  "phoneNumber": "+1234567890"
}

### Аутентификация обычного пользователя
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

> {%
client.global.set("user_token", response.body.token);
%}

### Аутентификация администратора
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}



### Создание первого дебетового счета
POST http://localhost:8080/api/debit-accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2MzY3NDA1NywiZXhwIjoxNzYzNjc3NjU3fQ.U15emtYK-8BcuvyNV3j3t4o46ggmoqcx86I51cRd7Js
Content-Type: application/json

{
  "balance": 0
}

> {%
client.global.set("account_number_1", response.body.accountNumber);
%}

### Создание второго дебетового счета
POST http://localhost:8080/api/debit-accounts
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "balance": 0
}

> {%
client.global.set("account_number_2", response.body.accountNumber);
%}

### Создание кредитного счета (только админ)
POST http://localhost:8080/api/credit-accounts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2MzkxNzAwMCwiZXhwIjoxNzYzOTIwNjAwfQ.rlW7GUSiLPChX-jdDPw3yx0v5AnMDbGuxzYKEJ1jzR0
Content-Type: application/json

{
}



### Пополнение первого счета
POST http://localhost:8080/api/transactions/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2MzkxMDM4OCwiZXhwIjoxNzYzOTEzOTg4fQ.Iu9WJg0AWya9Yb0rVB8_im_I7_Lo6xqyeRbqtzwFeLo
Content-Type: application/json

{
  "accountNumber": "0964374501",
  "amount": 5000,
  "comment": "Пополнение"
}

### Перевод между счетами
POST http://localhost:8080/api/transactions/transfer
Authorization: BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2MzkxMDEwNSwiZXhwIjoxNzYzOTEzNzA1fQ.zZk5JtvzR_DIb8usrQIuGGzJ2RZEVfjrN6YCImHM0is
Content-Type: application/json

{
  "fromAccount": "8049968259",
  "toAccount": "4724118063",
  "amount": 250,
  "comment": "Перевод"
}

### Снятие средств
POST http://localhost:8080/api/transactions/withdraw
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2MzY3NDA1NywiZXhwIjoxNzYzNjc3NjU3fQ.U15emtYK-8BcuvyNV3j3t4o46ggmoqcx86I51cRd7Js
Content-Type: application/json

{
  "accountNumber": "0964374508",
  "amount": 500,
  "comment": "Снятие"
}

### Увеличение кредитного лимита (только админ)
PUT http://localhost:8080/api/credit-accounts/{{credit_account_number}}/increase-limit?newLimit=6000.00
Authorization: Bearer {{admin_token}}

### Уменьшение кредитного лимита (только админ)
PUT http://localhost:8080/api/credit-accounts/{{credit_account_number}}/decrease-limit?newLimit=5500.00
Authorization: Bearer {{admin_token}}

### Установка процентной ставки (только админ)
PUT http://localhost:8080/api/credit-accounts/{{credit_account_number}}/set-interest?newRate=6.5
Authorization: Bearer {{admin_token}}

### Удаление кредитного счета (только админ)
DELETE http://localhost:8080/api/credit-accounts/{{credit_account_number}}
Authorization: Bearer {{admin_token}}

### Удаление дебетового счета
DELETE http://localhost:8080/api/debit-accounts/{{account_number_1}}
Authorization: Bearer {{user_token}}

### asdasd
POST http://localhost:8080/api/credit-accounts/accrue-interest
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MjcxNDE3MiwiZXhwIjoxNzYyNzE3NzcyfQ.Ukqwwvpya5IXEtoQ5-iiVE0OdZHpyS2hxyLWfsOYT5E

### asd
GET http://localhost:8080/api/transactions/getAll
Authorization: Bearer yJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2Mjk1MzI5MiwiZXhwIjoxNzYyOTU2ODkyfQ.y1jwpa-GK_aW9N9YDnXCi4YT4zaGtiJ-ezcHtxbssA0


